<ul>
<li>Version 0.1.0 6 August 2005 Initial beta release by Martin Vestergaard</li>
<li>Version 0.2.0 30 May 2011 Updates: current module API, preferences, styling, permissions etc</li>
<li>Version 0.2.1 30 August 2011 Split off action and method files, update js</li>
<li>Version 0.3.0 24 July 2012
<ul>
<li>Support smarty in answers</li>
<li>Also work on CMSMS 1.10 & 1.11</li>
</ul>
<li>Version 0.4.0 14 August 2012
<ul>
<li>Support reordering by table-DnD</li>
<li>Pattern and regex parameters for filtering questions</li>
<li>Re-factor code to improve "laziness"</li>
</ul>
</li>
<li>Version 0.4.1 14 September 2012
<ul>
<li>Bug-fixes</li>
</ul>
</li>
<li>Version 0.4.2 5 December 2012
<ul>
<li>Bug-fix: delete-question</li>
<li>Adjust styling to support FSCeditorX</li>
</ul>
</li>
<li>Version 0.5.0 31 March 2014
<ul>
<li>Code re-factored</li>
<li>Minor UI refinements</li>
<li>Support URL fragment like #Q or #C.Q to focus one question among others</li>
<li>Bug-fixes: UI-related and smarty-related</li>
</ul>
</li>
<li>Version 1.0 21 February 2015
<ul>
<li>Support multi-question [de]activation</li>
<li>Other minor UI refinements</li>
<li>Bug-fix: selection of category-owner</li>
<li>Updated tablednd plugin</li>
</ul>
</li>
</ul>
